runtime: python312
service: datagate-backend

env_variables:
  GCS_BUCKET_NAME: globaldashboard-4598e-direct-user-uploads
  FIREBASE_PROJECT_ID: globaldashboard-4598e
  PORT: 8080

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
